version: "3"

services:
  php-cockpit:
    image: "wodby/php:$PHP_TAG"
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mailhog-cockpit:1025"
      COLUMNS: 80
    volumes:
      - cockpit-sync:/var/www/html:cached

  nginx-cockpit:
    image: "wodby/nginx:$NGINX_TAG"
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php-cockpit
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php-cockpit
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - cockpit-sync:/var/www/html:cached
    ports:
      - "8088:80"
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=8088"
      - "traefik.frontend.rule=Host:${PROJECT_BASE_URL}"

  mailhog-cockpit:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - "8025:8025"
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}"

  traefik-cockpit:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  cockpit-sync:
    external: true
